#开发环境
#数据库的链接信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinemusic?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置springboot日志调试是否开启
debug: true


#设置打印日志级别，即打印sql语句
#日志级别trance debug info warn error
#基本日志
logging:
  level:
    root: info
    #扫描的包:druid.sql.Statement类和frank包
    druid:
      sql:
        Statement: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl